### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by LexQzim** [etiennedub/pyk4a#102]
Hey there, 

is there a way to capture the soundtrack from the Kinect? 
In this sense, is it also possible to activate or deactivate corresponding sensors, such as the microphone? 
If not, is this possibly planned for the future? 

Nice work btw. 
Thank you.

**Comment by lpasselin** [comment]
Hi,
Currently it is only possible to control the imu sensor, sorry

**Comment by shagren** [comment]
As I know microphone is separate device and you can use it as usual audio device.
