### ISSUE TITLE
How do I reference the 'pyk4a' library 

### ISSUE THREAD

**Issue by zhaocheng-hub** [etiennedub/pyk4a#111]
Hello, I have used some methods of 'pyk4a' library in my academic paper. How should I quote them in my paper?

**Comment by lpasselin** [comment]
You could use this:
````
@misc{pyk4a,
  author = {Louis-Philippe Asselin and Etienne Dubeau and Ilya Gruzinov},
  title = {pyk4a},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/etiennedub/pyk4a/}},
}
````

Or cite our papers (they do not mention the library but we developed pyk4a for them initially):
https://lvsn.github.io/real-svbrdf/
https://lvsn.github.io/rgbde_tracking/

Or footnote with url of the repository.

My Master's thesis briefly introduces pyk4a but it will only be published in a couple of weeks.

**Comment by lpasselin** [comment]
@shagren can you confirm you are ok with having your name in the citation?

**Comment by shagren** [comment]
@lpasselin , confirmed

**Comment by zhaocheng-hub** [comment]
@lpasselin  ok
