### ISSUE TITLE
Attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ZhengyangSun1020** [etiennedub/pyk4a#119]
Hi, I run into a problem about adding the body track package to main pyk4a package.
I used the code from readme:
`pip install -v --no-use-pep517 --no-build-isolation --upgrade git+https://github.com/etiennedub/pyk4a.git@feature/body-tracking --global-option="build_ext" --global-option="-ID:\Azure body track\sdk\include/" --global-option="-LD:\Azure body track\sdk\windows-desktop\amd64\release\lib/" --global-option="--enable-body-tracking"`

but the error is 
`ERROR: Command errored out with exit status 1: 'D:\anaconda1\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sunzh\\AppData\\Local\\Temp\\pip-req-build-kqx12t91\\setup.py'"'"'; __file__='"'"'C:\\Users\\sunzh\\AppData\\Local\\Temp\\pip-req-build-kqx12t91\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext '-ID:\Azure body track\sdk\include/' '-LD:\Azure body track\sdk\windows-desktop\amd64\release\lib/' --enable-body-tracking install --record 'C:\Users\sunzh\AppData\Local\Temp\pip-record-0whujtja\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\sunzh\AppData\Roaming\Python\Python38\Include\pyk4a' Check the logs for full command output.`

**Comment by ZhengyangSun1020** [comment]
There are many similar code with this error log like:
`from errors import K4AException, _verify_error`

it shows:
`ImportError: attempted relative import with no known parent package`

**Comment by ZhengyangSun1020** [comment]
And btw, if I wanna track human body movement, can this realize?

**Comment by ZhengyangSun1020** [comment]
Sorry to trouble you again

**Comment by lpasselin** [comment]
The body tracking is not fully supported yet. I won't be able to Help you much with this.

But the problem is the installation

**Comment by ZhengyangSun1020** [comment]
Okay, thank you!
