### ISSUE TITLE
Issue with calibration 3d_to2d

### ISSUE THREAD

**Issue by pingopalino1** [etiennedub/pyk4a#121]
Hello, 
I tried to convert coordinates of body joints to the 2d image and I wrote some short code to test the function. But I cannot get it to work. And I couldn't find an example of how to use this function in the examples. Could you please help me with the implementation. This is the code I wrote.

`
import cv2
import numpy as np

import pyk4a
from pyk4a import Config, PyK4A, calibration

kamera = PyK4A()

calibration.Calibration(calibration.CalibrationType.DEPTH,pyk4a.DepthMode.NFOV_UNBINNED,pyk4a.ColorResolution.OFF).convert_3d_to_2d([20,-200,1000], kamera)`

The error message is this: SystemError: <built-in function calibration_3d_to_2d> returned a result with an error set

Thanks for your help.

**Comment by shagren** [comment]
You need something like this
```python
kamera.open()
x,y = kamera.calibration.convert_3d_to_2d([20,-200,1000], CalibrationType.DEPTH)
```
