### ISSUE TITLE
 Module 'k4a_module' has no attribute 'is_body_tracking_supported'

### ISSUE THREAD

**Issue by ZhengyangSun1020** [etiennedub/pyk4a#124]
Hi, when I run the example code: pose_display_2d.py in body_tracking branch

I get this error: 

` File "D:\anaconda1\lib\site-packages\pyk4a\pyk4a.py", line 20, in PyK4A
    BODY_TRACKING_SUPPORT = k4a_module.is_body_tracking_supported()
AttributeError: module 'k4a_module' has no attribute 'is_body_tracking_supported'`

Do you know how to fix it?

**Comment by lpasselin** [comment]
You probably did not install the body tracking branch. Or your script is using pyk4a installed from pypi. See other PR related to body tracking please.

Body tracking is not fully supported yet.
