### ISSUE TITLE
Misalignment of depth and video frames

### ISSUE THREAD

**Issue by tquintudelft-source** [etiennedub/pyk4a#128]
I'm having this problem where the capture window for the lidar sensor and visual sensor are out of alignment:

![image](https://user-images.githubusercontent.com/72881961/120314184-410e1380-c2db-11eb-8840-6529cb6ed077.png)

I've worked with pyrealsense on the Intel L515 before and it has its own methods for frame alignment like so:

```
aligned_frames = self.align.process(frames)
color_frame = aligned_frames.get_color_frame()
 ```

Is there a similar solution in pyk4a or am I just doing something totally wrong?

This is how I am creating the camera object if it helps:

```
k4a = PyK4A(
            Config(
                color_resolution=pyk4a.ColorResolution.RES_720P,
                depth_mode=pyk4a.DepthMode.NFOV_UNBINNED,
                synchronized_images_only=True,
            )
        )
        k4a.start()
```

**Comment by shagren** [comment]
https://github.com/etiennedub/pyk4a/blob/8a2fb92f73067b97c35d82b337bc0d0920ffb5b7/example/viewer_transformation.py#L22

**Comment by shagren** [comment]
you can use `capture.transformed_color` or `capture.transformed_depth`

**Comment by tquintudelft-source** [comment]
Thanks!
