### ISSUE TITLE
Problem using k4a_module.transformation_depth_image_to_color_camera_custom

### ISSUE THREAD

**Issue by msqiu** [etiennedub/pyk4a#133]
I tried to transform the IR images but I found that if the corresponding depth pixels are missing, the IR pixels will be 0.

update:
I found the reason:

> The function k4a_calibration_2d_to_2d() converts a 2D pixel coordinate of the source camera to a 2D pixel coordinate of the target camera. Source and target must be set to color or depth camera. The function requires the pixel’s depth value (in millimeters) in the source camera image as an input, one way to derive the depth value in the color camera geometry is to use the function k4a_transformation_depth_image_to_color_camera(). It calls k4a_calibration_2d_to_3d() to convert to a 3D point of the source camera system. It then calls k4a_calibration_3d_to_2d() to convert to a 2D pixel coordinate of the target camera image. The valid value is set to 0, if k4a_calibration_2d_to_3d() or k4a_calibration_3d_to_2d() returns an invalid result.

https://docs.microsoft.com/en-us/azure/kinect-dk/use-calibration-functions

**Comment by lpasselin** [comment]
Hi, is this still an issue?

**Comment by msqiu** [comment]
No, you can close the issue now:)
