### ISSUE TITLE
How about point cloud?

### ISSUE THREAD

**Issue by wangmiaowei** [etiennedub/pyk4a#136]
Is there any way to get point cloud from Azure Kinect .mkv file?

**Comment by chrismeunier** [comment]
Sure you can use the code in [example/playback.py](https://github.com/etiennedub/pyk4a/blob/8a2fb92f73067b97c35d82b337bc0d0920ffb5b7/example/playback.py#L16) and recover the point cloud with `capture.depth_point_cloud`.

Simplest way to test it I can think of:
```python
from pyk4a import PyK4APlayback

playback= PyK4APlayback('your_path_to_mkv_file')
playback.open()

while True:
    try:
        capture = playback.get_next_capture()
        if capture.depth_point_cloud is not None:
            point_cloud = capture.depth_point_cloud
            # then do what you want
    except EOFError:
        break
```

**Comment by wangmiaowei** [comment]
Thanks for your suggestion. I'd like to try it.

**Comment by wangmiaowei** [comment]
@lpasselin  Is there any function to save the points file?

**Comment by lpasselin** [comment]
Any method to save a numpy array will work.

**Comment by wangmiaowei** [comment]
Thanks for your reply. Is there any function in this python wrap to transform the depth image to PointCloud?
