### ISSUE TITLE
depth_image_to_color_camera example

### ISSUE THREAD

**Issue by zbs881314** [etiennedub/pyk4a#143]
Do you have any depth_image_to_color_camera related examples  that you can share with me. I don't know how to use it

**Comment by shagren** [comment]
https://github.com/etiennedub/pyk4a/blob/master/example/viewer_transformation.py

**Comment by zbs881314** [comment]
I need to get the depth data from depth_image_to_color_camera, So how do I extract the transformed depth data？

**Comment by zbs881314** [comment]
frame = colorize(capture.transformed_depth, (None, 5000))
cv2.imwrite('image/'+ str(1) + '.jpg', frame) #存储为图像

**Comment by lpasselin** [comment]
I assume your last message is working code. Reopen if required.
