### ISSUE TITLE
I wonder if Kinect can adjust FOV

### ISSUE THREAD

**Issue by Qiu731** [etiennedub/pyk4a#156]
Sorry to bother you. I think Kinect's FOV is too large for me, which will make the objects in the picture look very small. I wonder if I can set FOV?

**Comment by lpasselin** [comment]
Yes but only the depth FOV. See config.py DepthMode

FOV are detailed here:
https://docs.microsoft.com/en-us/azure/kinect-dk/hardware-specification#depth-camera-supported-operating-modes
