### ISSUE TITLE
why the coordinate of the depth camera is the opposite of the RGB?

### ISSUE THREAD

**Issue by hlyf-xs** [etiennedub/pyk4a#161]
I confused that the coordinate of the depth camera is the opposite of the RGB, for example, the depth value of the coordinate color[x][y] is depth[y][x].

**Comment by rajkundu** [comment]
I think it could just be a coincidence. In general, to access the values of pixel (x, y) in an image, use `image[y][x]` (or, equivalently, `image[y,x]`). If you print out `color.shape` (assuming `color` is a numpy array), you should see that its shape is `(height, width, 4)`. So, to access each of the 4 B/G/R/A values at pixel (x, y) of the color image, use`color[y][x]` or `color[y,x]`.

To get the depth value at that pixel, you must first *transform* the depth image into the frame of the color image. To do this, `pyk4a` conveniently provides [`capture.transformed_depth`](https://github.com/etiennedub/pyk4a/blob/905d77bfecc0ec425a6335dcddbd63cb09314334/pyk4a/capture.py#L131), allowing you to get the raw depth data at color pixel (x, y) using the expression `capture.transformed_depth[y,x]`. However, **this is not a 3D depth** in meters/millimeters. You will need to use other transformations/functions to get the 3D coordinates of color pixel (x, y).
