### ISSUE TITLE
May solve the problem of "cannot import k4a_module"

### ISSUE THREAD

**Issue by LinyeLi60** [etiennedub/pyk4a#167]
Some windows users suffer from the problem that can not import k4a_module, I think it may be caused by anaconda [https://github.com/ContinuumIO/anaconda-issues/issues/12475](https://github.com/ContinuumIO/anaconda-issues/issues/12475).

**Comment by rajkundu** [comment]
I can confirm that I have this issue and that setting `CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1` as per your link fixed it for me. Thank you!

**Comment by lpasselin** [comment]
Wow finally an answer to the anaconda problem! Let's add this information to the README.
Thanks a lot for taking the time to write here, both of you.

**Comment by lpasselin** [comment]
Added info in the README, in dev.
