### ISSUE TITLE
errors when config the depth_mode of the pyk4a as WFOV_UNBINNED

### ISSUE THREAD

**Issue by leilei-fu** [etiennedub/pyk4a#179]
When I am trying to config the pyk4a as WFOV_UNBINNED, there raises an error. Default config or NFOV_UNBINNED is OK.
![f994fa886a6a018a2a32a774431f460](https://user-images.githubusercontent.com/62886980/193443061-00319c02-3eba-4336-95b0-8a2f0ad75739.png)

**Comment by lpasselin** [comment]
Weird but. Not sure how to help you.

Did you install the pyk4a package or the bundle?

**Comment by lpasselin** [comment]
Do you remember what version of the SDK were you using?
