### ISSUE TITLE
pyk4a raises an error when Depth mode is set to 0 (Depth is off) 

### ISSUE THREAD

**Issue by crypto-g245** [etiennedub/pyk4a#182]
Pyk4a is throwing below exception while setting depth mode to OFF. 

![image](https://user-images.githubusercontent.com/51653105/199507100-05ea1086-1b23-47e5-b9b9-451717670ae6.png)

**Comment by lpasselin** [comment]
What version of the SDK do you have? Normally you should see error logs from the SDK when there are errors like this.
