### ISSUE TITLE
Question about Library

### ISSUE THREAD

**Issue by AnthonyP1212** [etiennedub/pyk4a#183]
Hello,

This isn't an issue as much as it's a question. If this is the wrong place to be asking, forgive me, I am new to GitHub. I want to use this wrapper with the Azure Kinect camera so I can capture depth data for a Keypoint detection model. I am currently using Google's Mediapipe keypoint detection model which returns x, y and z coordinates of the Key-points. Is there a way I can use this wrapper to capture Z coordiante of the key points?

Thank you very much.

**Comment by lpasselin** [comment]
Not sure I understand your question. This library is a wrapper over the kinect azure device SDK.
