### ISSUE TITLE
Depth image counts to units conversion

### ISSUE THREAD

**Issue by vstadnytskyi** [etiennedub/pyk4a#205]
Hi,

Do we know what is the conversion factor between counts (unsigned integer 16) in Azure Kinect DK? The _capture_ object does not have a field for it. Is it in millimeters?

Thank you

**Comment by vstadnytskyi** [comment]
I have done few tests. I have a motorized stage and if I move by 10 mm away from my target, the number changes by 10-11 counts. From this I can conclude that the returned integer values in the depth image are indeed millimeters.

Can anyone else confirm it?

**Comment by lpasselin** [comment]
Yes, this is mentionned in the official documentation of the kinect azure. It is in mm.
