### ISSUE TITLE
specify the path for my k4a.dll

### ISSUE THREAD

**Issue by TitansWhale** [etiennedub/pyk4a#222]
I want to integrate the SDK into my software. How should I specify the path for my k4a.dll?

**Comment by spike3d** [comment]
refer to : https://www.orbbec.com/documentation/access-akdk-application-software-with-femto-bolt/

**Comment by TitansWhale** [comment]
```
import os
from pathlib import Path

# 指定lib目录为dll目录
os.environ['K4A_DLL_DIR'] = str(Path('lib').absolute())

import pyk4a

```
