### ISSUE TITLE
There is a problem with _get_capture_depth

### ISSUE THREAD

**Issue by lh784116211** [etiennedub/pyk4a#29]
When I use viewer.py in the example file, I can get a color image, but I get an error when I get a depth image。There is a problem with _get_capture_depth
![image](https://user-images.githubusercontent.com/46106400/82005135-32849800-9697-11ea-9a3e-88d99fcf843b.png)

**Comment by lh784116211** [comment]
![Snipaste_2020-05-15_10-31-51](https://user-images.githubusercontent.com/46106400/82005187-51832a00-9697-11ea-9885-60b55144162e.png)

**Comment by lpasselin** [comment]
What version(s) did you install? From pypi or from our github develop branch?
