### ISSUE TITLE
Mutable default argument in PyK4A

### ISSUE THREAD

**Issue by DominikMa** [etiennedub/pyk4a#43]
Thank you for this great library!
I might found the following bug:

In
https://github.com/etiennedub/pyk4a/blob/887d89bedf1854a89d31ad4932399ca7c6f2393b/pyk4a/pyk4a.py#L27
the default for `config` is an mutable object. Therefore every other instance with no argument for `config` shares this single object.

I don't think that this is intentional, if it is I do not understand why.
The most common pattern I know for this would be:
```python
def __init__(self, config=None, device_id=0):
    if not config:
        config = Config()
```
or
```python
def __init__(self, config=None, device_id=0):
    self.config = config if config else Config()
```
if you prefer a one liner.

For a better explanation of this problem see https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

**Comment by lpasselin** [comment]
You are right, this can be problematic. Thanks!
