### ISSUE TITLE
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

### ISSUE THREAD

**Issue by zhaoyuliang5** [etiennedub/pyk4a#5]
color = k4a_module.device_get_color_image()
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

**Comment by lpasselin** [comment]
You are on windows?

**Comment by lpasselin** [comment]
Latest pip release was not up to date with fixes for windows in recent commits.
It will be available soon today. @etiennedub

**Comment by etiennedub** [comment]
I will close this issue for now. If the problem is still there, @zhaoyuliang5 you can reopen it.
