### ISSUE TITLE
Calibration conversion 2d and 3d takes integers as source points

### ISSUE THREAD

**Issue by lpasselin** [etiennedub/pyk4a#52]
Should `source_points` be floats instead of integers? Both the inputs and outputs of the related SDK functions are floats?

https://github.com/etiennedub/pyk4a/blob/develop/pyk4a/calibration.py#L33

https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___functions_gaacd1eab997ef964b5e436afa5295726e.html#gaacd1eab997ef964b5e436afa5295726e

**Comment by etiennedub** [comment]
Yes you are right. We should change for float in the c code. Also, I noted that the thread_safe arg is missing in the python function. I open issue #55  for that.

**Comment by lpasselin** [comment]
will be fixed in https://github.com/etiennedub/pyk4a/pull/57
