### ISSUE TITLE
Functions in calibration.py should pass thread_safe in args

### ISSUE THREAD

**Issue by etiennedub** [etiennedub/pyk4a#55]
Functions in the file [calibration.py](https://github.com/etiennedub/pyk4a/blob/develop/pyk4a/calibration.py) should pass the argument `thead_safe` because it's expected in the low level [c functions](https://github.com/etiennedub/pyk4a/blob/develop/pyk4a/pyk4a.cpp#L608).

**Comment by lpasselin** [comment]
Will be fixed with https://github.com/etiennedub/pyk4a/pull/57
