### ISSUE TITLE
Loading DLL fails in Python 3.8.5 on windows

### ISSUE THREAD

**Issue by matnilswe** [etiennedub/pyk4a#60]
Python 3.8.5 (with venv)
when importing: 
from pyk4a import PyK4A
I hit the issue:
"DLL load failed while importing k4a_module: The specified module could not be found"

DLL loading works when installing and importing from Python 3.7.5

**Comment by lpasselin** [comment]
First time I hear this. Not sure how to help you.

Is python 3.7.5 also with venv?

Is it possible that the venv with python 3.8 tries to reuse the 3.7.5 version? Maybe try uninstalling and reinstalling using `--upgrade` ?

Can you try installing from the develop branch?

**Comment by matnilswe** [comment]
The 3.7.5 Python I tried was in a conda environment. To be clear this is what I tried after failing with the Python 3.8.5 with venv. Don't think that the issue has anything to do with "reuse".  Hard to see exactly what fails since it's in "k4a_module.cp38-win_amd64.pyd" I guess.

**Comment by lpasselin** [comment]
Which pip version are you using?

**Comment by matnilswe** [comment]
pip 20.2.2

**Comment by matnilswe** [comment]
FYI. upgraded to pip 20.2.3. 
Issue remains.

**Comment by lpasselin** [comment]
I'm really not a windows expert.

`DLL load failed while importing k4a_module: The specified module could not be found` Is this related to the depthengine DLL?

There is a similar issue here https://github.com/etiennedub/pyk4a/issues/14

**Comment by lpasselin** [comment]
@shagren do you know how to fix this? multiple users have the problem.

**Comment by shagren** [comment]
@matnilswe , can you check this version: https://github.com/etiennedub/pyk4a/pull/68 ?

**Comment by lpasselin** [comment]
Might be solved in master with https://github.com/etiennedub/pyk4a/pull/68
Would you mind trying to install with the command in the README?

**Comment by matnilswe** [comment]
Used the install command you suggested. pip install pyk4a --no-use-pep517 --global-option=build_ext --global-option="-IC:\Program Files\Azure Kinect SDK v1.4.0\sdk\include" --global-option="-LC:\Program Files\Azure Kinect SDK v1.4.0\sdk\windows-desktop\amd64\release\lib"

Import seems to work now. Thanks! :-)

**Comment by matnilswe** [comment]
Eh, I must have tried it in my anaconda env. Seems to work on 3.8.2 anaconda, but now I seem to still have the same issue in my venv for 3.8.5. Sorry about the confusion.

**Comment by ozgucbertug** [comment]
This issue still persists. Building the library works fine however when I try to run the example code on Windows, I receive ImportError: DLL load failed while importing k4a_module: The specified module could not be found.
