### ISSUE TITLE
transform the local depth image from the viewpoint of the depth camera into the viewpoint of the color camera

### ISSUE THREAD

**Issue by Diananini** [etiennedub/pyk4a#77]
Thanks for your wonderful work!
I extracted depth and images from .mkv (recorded with the k4arecorder tool), but the pixels of the two images do not correspond to each other. How to transform the **local depth image** from the viewpoint of the depth camera into the viewpoint of the color camera?

**Comment by shagren** [comment]
Please check `depth_image_to_color_camera()`
Required `calibration` argument can be retrieved from `PyK4APlayback.calibration`.

**Comment by Diananini** [comment]
Thanks very much! It really works!
