### ISSUE TITLE
DLL load failed while importing k4a_module

### ISSUE THREAD

**Issue by ozgucbertug** [etiennedub/pyk4a#80]
Building the library works fine however when I try to run the example code on Windows, I receive ImportError: DLL load failed while importing k4a_module: The specified module could not be found. Seems like #60 issues still persist. I am using python version 3.8.5

File "c:\Users\Ozguc\Documents\GitHub\KinectAzureDepthMapping\main.py", line 1, in <module>
    from pyk4a import PyK4A
  File "C:\Users\Ozguc\anaconda3\envs\azure\lib\site-packages\pyk4a\__init__.py", line 1, in <module>
    from .calibration import Calibration, CalibrationType
  File "C:\Users\Ozguc\anaconda3\envs\azure\lib\site-packages\pyk4a\calibration.py", line 4, in <module>
    import k4a_module
ImportError: DLL load failed while importing k4a_module: The specified module could not be found.

**Comment by lpasselin** [comment]
Did you try with pip option --no-use-pep517 ?

Also what is your pip version?

**Comment by ozgucbertug** [comment]
I've tried with the option --no-use-pep517 on pip version 20.2.4. Today I've created a new environment and re-entered the DLL directory to PATH. This solved the issue.

**Comment by bibeglimbu** [comment]
Hello,
I am having this same issue how ever no matter how many times i recreate the virtual env, it doesnt work....any details?
