### ISSUE TITLE
Multiple applications in parallel

### ISSUE THREAD

**Issue by saurabbhsp** [etiennedub/pyk4a#83]
Hi,
Is it possible for multiple applications to access the Kinect stream in parallel ?

**Comment by lpasselin** [comment]
I don't think this is possible with the kinect SDK.
You could test with the viewer of the SDK.
iirc it is not possible to open the same device twice in two SDK viewers.

There are some multiprocessing examples for pyk4a if that's what you are looking for.

**Comment by gengauss** [comment]
@lpasselin where can I find the multiprocessing examples for pyk4a? Thank you

**Comment by lpasselin** [comment]
See examples directory
