### ISSUE TITLE
Misalignment between depth and RGB after transforming depth to RGB camera

### ISSUE THREAD

**Issue by jsaisagar** [etiennedub/pyk4a#84]
Hi,

I am getting misalignment between RGB and depth outputs after "using capture.transformed_depth". Any inputs on how to resolve this issue?

Thanks,
Sai

**Comment by lpasselin** [comment]
Would you mind sharing example images for RGB, depth and transformed_depth?

**Comment by jsaisagar** [comment]
Hi Lpasselin,

I have used low light just to capture misalignment on edges. However, same is observed with sufficient lighting. I am attaching RGB and transformed depth.

![rgb_0](https://user-images.githubusercontent.com/6646353/100956639-e7e94100-353e-11eb-8d22-08afae880afd.png)
![tdepth_0](https://user-images.githubusercontent.com/6646353/100956643-e9b30480-353e-11eb-8341-a68f65274fb1.png)

Thanks for any help.

**Comment by lpasselin** [comment]
I think this is normal behavior unfortunately. The transformed_depth seems to be doing it's job.

The calibration is not perfect and maybe you can refine it with a custom calibration.

@etiennedub can you confirm?

**Comment by jsaisagar** [comment]
May I know which is the best way to refine calibration between RGB and Depth cameras to reduce this misalignment?

Thanks,
