### ISSUE TITLE
How do I get a depth value from a depth image.

### ISSUE THREAD

**Issue by zhaocheng-hub** [etiennedub/pyk4a#85]
Hello, 

how do I get the depth value at a certain point from the depth image that I get in my code?

How do I use this library to generate point cloud images?

Thanks,

**Comment by lpasselin** [comment]
Hi, please see the various examples. You can browse the code of the library itself.
We use typical numpy arrays as image structure, which is very common with python.
Maybe you should look into opencv tutorials.

**Comment by zhaocheng-hub** [comment]
> 
> 
> Hi, please see the various examples. You can browse the code of the library itself.
> We use typical numpy arrays as image structure, which is very common with python.
> Maybe you should look into opencv tutorials.

Thank you very much for your advice.
