### ISSUE TITLE
Helpers library needed

### ISSUE THREAD

**Issue by lightov73** [etiennedub/pyk4a#94]
I'm trying to use the pyk4a example regarding the depth image demo and there is a reference there to helpers library . To which helpers library it refers ? Can you help with a link to it's intsallation?

**Comment by lpasselin** [comment]
The examples (and their utile helper file) are not included in the library itself when you install from pypi.
I take a note to add this information to the readme.

https://github.com/etiennedub/pyk4a/blob/master/example/helpers.py
