### ISSUE TITLE
How to output a depth image of float type?

### ISSUE THREAD

**Issue by zxx0102** [etiennedub/pyk4a#98]
How to output a depth image of float type?

**Comment by lpasselin** [comment]
Hi, the depth sensor returns values in integers. You won't get more
precision than integers in mm with the Kinect azure.

If you want to convert depth to floats, you can do

`capture.depth.astype(np.float32)`

**Comment by shagren** [comment]
```
depth_in_meters = depth / 1000 # numpy magic
```
